spring:
  datasource:
    username: bookadmin
    password: password
    url: jdbc:mysql://127.0.0.1:3306/bookdb?useUnicode=true&characterEncoding=UTF-8
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate

  liquibase:
    user: bookadmin
    password: password