spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true

  liquibase:
    change-log: db/changelog/changelog-master.xml

logging.level:
  org.hibernate.type.descriptor.sql: info